<?php
/**
 * Created by PhpStorm.
 * User: execut
 * Date: 11/8/17
 * Time: 5:10 PM
 */

namespace execut\oData;


use yii\base\Component;

class Client extends Component
{
    public $host = null;
    public $path = null;
    public $options = [];
    public $customColumnsTypes = [];
    protected $_client = null;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $profiler = new Profiler();
        $this->_client = new \Kily\Tools1C\OData\Client(trim($this->host, '/') . '/' . $this->path, $this->options, $profiler);
    }

    public function __call($name, $params)
    {
        return call_user_func_array([$this->_client, $name], $params);
    }

    public function __get($name)
    {
        return $this->_client->$name;
    }
}